### ISSUE TITLE
Sobre tu markdown

### ISSUE THREAD

**Issue by DianaCarrillo** [Esthela1/cdmx-2018-01-FE-markdown#6]
Hola Esthela, sobre lo que vimos en el code review puedo aconsejarte que primero hagas un pseudocódigo, si quieres podemos trabajarlo juntas. Apóyate en nosotras y revisa nuestros repositorios, recuerda eso es válido y es muy útil para vvisualizar una solución para tu proyecto.

**Comment by Esthela1** [comment]
Gracias por tu aportación, claro, me apoyaré en ustedes y seguiré tu consejo.
