### ISSUE TITLE
Feed back

### ISSUE THREAD

**Issue by Anavzqz** [Esthela1/cdmx-2018-01-FE-markdown#7]
Hola Esthela,
Mi feed back para ti es que considero que, sería bueno que te apoyaras en nostras (tu squad), el squad es para apoyarnos para avanzar juntas y sobre todo aprender mucho!
Te he visto trabajando y dedicándole varías horas al proyecto, si lo combinas apoyándote en nosotras, creo que puedes tener buenos resultados.

**Comment by Esthela1** [comment]
Gracias, si, ya he estado pidiendo apoyo y tienes toda la razón
