### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by DiLeyRa** [Esthela1/cdmx-2018-01-FE-markdown#8]
Hola Esthela

Mi principal comentario es que debes de acercarte a pedir ayuda cuando creas que la nececitas, para poder atender a tiempo los problemas que se te presenten, todas avanzamos a distinto ritmo, pero lo importante es seguir avanzando y no quedarnos estancadas....... VAMOS HACIA ADELANTE  ; )

**Comment by Esthela1** [comment]
Gracias, si he visto la diferencia ahora que me están apoyando
