### ISSUE TITLE
Preguntanos!!!

### ISSUE THREAD

**Issue by BrisiaCastrejon** [Esthela1/cdmx-2018-01-FE-markdown#9]
Hola Esthela;
Básicamente mi comentario es lo que nuestro squad te ha comentado, me gustaría que tuvieras más confianza en preguntar, claro que nosotras no lo sabemos todo, pero justamente por eso podríamos hacer un frente unido para solucionar el punto en el que te encuentres bloqueada, recuerda que siempre te vamos a decir que SÍ, porque eso nos ayuda a nosotras tanto como a ti.

**Comment by Esthela1** [comment]
Gracias Briss, claro que si.
